version: "3.9"

services:
  dashboard:
    image: factory-of-the-future
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build: .
    command: ./dashboard
  factory_1:
    image: factory-of-the-future
    command: ./factory 172.25.0.2
#    volumes:
#      - type: bind
#        source: ./sensor_history.dat
#        target: /code/sensor_history.dat
    depends_on:
      - dashboard
  #factory_2:
  #  build: .
  #  command: ./factory_test 172.25.0.2
  #  volumes:
  #    - fact2:/code
  #  depends_on:
  #    - dashboard
  ml:
    image: factory-of-the-future
    command: ./ml 172.25.0.2
    #volumes:
    #  - ml:/code
    depends_on:
      - dashboard
volumes:
  fact1:
  fact2:
  ml: